<?php

namespace AppBundle\Repository;

/**
 * JugadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JugadaRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Obtiene todas las jugadas de una determinada partida
     *
     * @param $id
     * @return mixed
     */
    public function getJugadasPartida($id)
    {
        // Todas las jugadas de una determinada partida
        $result = $this->getEntityManager()
            ->createQuery('SELECT j.id, j.idPartida, j.fechaAccion, CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(j.color1,\', \'),j.color2),\', \'),j.color3),\', \'),j.color4),\', \'),j.color5),\', \'),j.color6) as apuesta, j.resultado FROM 
AppBundle\Entity\Jugada j WHERE j.idPartida = :idPartida')
            ->setParameter('idPartida', $id)
            ->getResult();

        return isset($result[0]) ? $result : null;
    }

    public function getAllJugadas()
    {
        return $this->getEntityManager()
            ->createQuery('SELECT j.id, j.idPartida, j.fechaAccion, CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(j.color1,\', \'),j.color2),\', \'),j.color3),\', \'),j.color4),\', \'),j.color5),\', \'),j.color6) as apuesta, j.resultado FROM 
AppBundle\Entity\Jugada j')
            ->getResult();
    }

    public function getJugada($id)
    {
        return $this->getEntityManager()
            ->createQuery('SELECT j.id, j.idPartida, j.fechaAccion, CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(CONCAT(j.color1,\', \'),j.color2),\', \'),j.color3),\', \'),j.color4),\', \'),j.color5),\', \'),j.color6) as apuesta, j.resultado FROM 
AppBundle\Entity\Jugada j WHERE j.id = :idJugada')
            ->setParameter('idJugada', $id)
            ->getResult();
    }
}
